pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        NEXUS_URL = "http://localhost:8081"
        NEXUS_REPO = "maven-releases"
        NEXUS_CREDENTIALS = "nexus-credentials"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/fischere5-boop/demo.git'
            }
        }

        stage('Build JAR') {
            steps {
                sh "mvn clean package -DskipTests"
            }
        }

        stage('Upload to Nexus') {
            steps {
                script {
                    // Find the jar file generated by Maven
                    def jarFile = sh(script: "ls target/*.jar", returnStdout: true).trim()
                    echo "Uploading: ${jarFile}"

                    withCredentials([
                        usernamePassword(
                            credentialsId: env.NEXUS_CREDENTIALS,
                            usernameVariable: 'admin',
                            passwordVariable: '1234qwer'
                        )
                    ]) {

                        sh """
                        mvn deploy:deploy-file 
                          -Dfile=${jarFile} 
                          -DrepositoryId=${hw6} 
                          -Durl=${http://localhost:8081/repository/hw6/}/repository/${hw6}/ 
                          -DgroupId=com.example.demo 
                          -DartifactId=demo 
                          -Dversion=1.0.0 
                          -Dpackaging=jar 
                          -DgeneratePom=true 
                          -Dusername=$admin 
                          -Dpassword=$1234qwer
                        """
                    }
                }
            }
        }
    }
}
